"""add used_for_playlist_datetime column

Revision ID: 378cfaa2c1f4
Revises: 30596ea39e44
Create Date: 2026-01-05 16:28:14.788535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '378cfaa2c1f4'
down_revision: Union[str, Sequence[str], None] = '30596ea39e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('used_for_playlist_datetime', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'used_for_playlist_datetime')
    # ### end Alembic commands ###
