import os
from dotenv import load_dotenv

load_dotenv()

ARTIST_DATABASE_ID = os.getenv('ARTIST_DATABASE_ID')
SPOTIPY_CLIENT_ID = os.getenv('SPOTIPY_CLIENT_ID')
SPOTIPY_CLIENT_SECRET = os.getenv('SPOTIPY_CLIENT_SECRET')
SPOTIPY_REDIRECT_URI = os.getenv('SPOTIPY_REDIRECT_URI')

PLAYLIST_ID = '1wVT9oPaOYQfLxMMdC2EJg'
